"use client";

/**
 * TruthStateBanner — [P0-006 / P1-015 REMEDIATION 2026-08]
 * -----------------------------------------------------------------------------
 * Persistent, unmissable banner that states EXACTLY what the operator is
 * looking at. Previously the app could silently render simulated telemetry
 * with quality "VALID" and a tiny "mock" suffix in the header — simulation
 * was confusable with production truth (directive §1: "the dashboard must
 * never present simulated data as valid real-time physical truth").
 *
 * Priority (highest first):
 *   1. SIMULATION — envelope generated by the demo store
 *   2. NO_DATA    — no real telemetry available
 *   3. OFFLINE    — transport down, last-known values shown
 *   4. STALE      — newest telemetry older than 60 s
 */
import { computeFreshness } from "@/lib/types";
import { useLanguage } from "@/components/providers/language-provider";

interface TruthStateBannerProps {
  simulated?: boolean;
  online?: boolean;
  timestamp?: number | null;
  /** Called on every render tick by the parent's polling cadence. */
  now?: number;
}

export function TruthStateBanner({
  simulated,
  online,
  timestamp,
  now,
}: TruthStateBannerProps) {
  const { t } = useLanguage();

  if (simulated) {
    return (
      <div
        role="status"
        aria-live="polite"
        className="w-full bg-amber-500/15 border border-amber-500/50 text-amber-600 dark:text-amber-400 px-4 py-2 text-center text-sm font-semibold tracking-wide"
        data-testid="simulation-banner"
      >
        {t("common.simulation_banner")}
      </div>
    );
  }

  const freshness = computeFreshness(timestamp, { now });

  if (freshness === "NO_DATA") {
    return (
      <div
        role="status"
        aria-live="polite"
        className="w-full bg-red-500/10 border border-red-500/40 text-red-600 dark:text-red-400 px-4 py-2 text-center text-sm font-semibold tracking-wide"
        data-testid="nodata-banner"
      >
        {t("common.no_data_banner")}
      </div>
    );
  }

  if (online === false) {
    return (
      <div
        role="status"
        aria-live="polite"
        className="w-full bg-orange-500/10 border border-orange-500/40 text-orange-600 dark:text-orange-400 px-4 py-2 text-center text-sm font-semibold tracking-wide"
        data-testid="offline-banner"
      >
        {t("common.offline_banner")}
      </div>
    );
  }

  if (freshness === "STALE") {
    return (
      <div
        role="status"
        aria-live="polite"
        className="w-full bg-yellow-500/10 border border-yellow-500/40 text-yellow-700 dark:text-yellow-400 px-4 py-2 text-center text-sm font-semibold tracking-wide"
        data-testid="stale-banner"
      >
        {t("common.stale_banner")}
      </div>
    );
  }

  return null;
}
